# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worldtime.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='worldtime.proto',
  package='WorldTime',
  syntax='proto3',
  serialized_options=_b('\252\002\016WorldTime.gRPC'),
  serialized_pb=_b('\n\x0fworldtime.proto\x12\tWorldTime\"#\n\x0eWorldTimeReply\x12\x11\n\tlocaltime\x18\x01 \x01(\t\",\n\x05Point\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x32\x43\n\tWorldTime\x12\x36\n\x07GetTime\x12\x10.WorldTime.Point\x1a\x19.WorldTime.WorldTimeReplyB\x11\xaa\x02\x0eWorldTime.gRPCb\x06proto3')
)




_WORLDTIMEREPLY = _descriptor.Descriptor(
  name='WorldTimeReply',
  full_name='WorldTime.WorldTimeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localtime', full_name='WorldTime.WorldTimeReply.localtime', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=65,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='WorldTime.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='WorldTime.Point.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='WorldTime.Point.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['WorldTimeReply'] = _WORLDTIMEREPLY
DESCRIPTOR.message_types_by_name['Point'] = _POINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorldTimeReply = _reflection.GeneratedProtocolMessageType('WorldTimeReply', (_message.Message,), dict(
  DESCRIPTOR = _WORLDTIMEREPLY,
  __module__ = 'worldtime_pb2'
  # @@protoc_insertion_point(class_scope:WorldTime.WorldTimeReply)
  ))
_sym_db.RegisterMessage(WorldTimeReply)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'worldtime_pb2'
  # @@protoc_insertion_point(class_scope:WorldTime.Point)
  ))
_sym_db.RegisterMessage(Point)


DESCRIPTOR._options = None

_WORLDTIME = _descriptor.ServiceDescriptor(
  name='WorldTime',
  full_name='WorldTime.WorldTime',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=113,
  serialized_end=180,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTime',
    full_name='WorldTime.WorldTime.GetTime',
    index=0,
    containing_service=None,
    input_type=_POINT,
    output_type=_WORLDTIMEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORLDTIME)

DESCRIPTOR.services_by_name['WorldTime'] = _WORLDTIME

# @@protoc_insertion_point(module_scope)
