# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import worldtime_pb2 as worldtime__pb2


class WorldTimeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTime = channel.unary_unary(
        '/WorldTime.WorldTime/GetTime',
        request_serializer=worldtime__pb2.Point.SerializeToString,
        response_deserializer=worldtime__pb2.WorldTimeReply.FromString,
        )


class WorldTimeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WorldTimeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetTime,
          request_deserializer=worldtime__pb2.Point.FromString,
          response_serializer=worldtime__pb2.WorldTimeReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'WorldTime.WorldTime', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
